CREATE TABLE customer
(
    id      BIGINT NOT NULL,
    name    VARCHAR(255),
    project VARCHAR(255),
    CONSTRAINT pk_customer PRIMARY KEY (id)
);

CREATE TABLE project
(
    id         BIGINT       NOT NULL,
    name       VARCHAR(255) NOT NULL,
    start_date date,
    manager_id BIGINT,
    CONSTRAINT pk_project PRIMARY KEY (id)
);

CREATE TABLE ticket
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY NOT NULL,
    start_date  date,
    end_date    date,
    assignee_id BIGINT,
    project_id  BIGINT,
    CONSTRAINT pk_ticket PRIMARY KEY (id)
);

ALTER TABLE project
    ADD CONSTRAINT FK_PROJECT_ON_MANAGER FOREIGN KEY (manager_id) REFERENCES customer (id);

ALTER TABLE ticket
    ADD CONSTRAINT FK_TICKET_ON_ASSIGNEE FOREIGN KEY (assignee_id) REFERENCES customer (id);

ALTER TABLE ticket
    ADD CONSTRAINT FK_TICKET_ON_PROJECT FOREIGN KEY (project_id) REFERENCES project (id);